# Generated by Django 3.2.3 on 2021-05-17 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfileapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuploadfile',
            name='f_name',
        ),
    ]
